from __future__ import annotations

from src.data.state import SymbolState
from src.execution.order_state import QuoteTarget
from src.strategy.base import StrategyDecisionTrace, StrategyDiagnostics
from src.strategy.mm_pipeline import MarketMakingQuotePlan
from src.strategy.params import StrategyParameterBundle, SymbolStrategyParameters


def build_market_making_trace(
    *,
    symbol: str,
    strategy_name: str,
    model_version: str,
    state: SymbolState,
    bundle: StrategyParameterBundle,
    plan: MarketMakingQuotePlan,
    gate_reason: str,
    target: QuoteTarget,
    inventory_lots: int,
    book_age_ms: float,
    spread_ticks: float,
) -> StrategyDecisionTrace:
    params = bundle.values
    return StrategyDecisionTrace(
        symbol=symbol,
        strategy_name=strategy_name,
        model_version=model_version,
        decision_reason=plan.reason,
        diagnostics=StrategyDiagnostics(
            fair_value_anchor=state.mid_price,
            fair_value_center=plan.center,
            quote_width=plan.quote_width,
            inventory_skew=plan.inventory_skew,
            alpha_bias=plan.imbalance_shift,
            toxicity_score=params.toxicity_score,
            regime_code=gate_reason,
            allocation_weight=params.allocation_weight,
            pace_multiplier=params.pace_multiplier,
            participation_mode=plan.participation_mode,
            parameter_source=bundle.source,
            parameter_version=bundle.version,
            extra=build_market_making_trace_extra(
                state=state,
                params=params,
                plan=plan,
                inventory_lots=inventory_lots,
                book_age_ms=book_age_ms,
                spread_ticks=spread_ticks,
            ),
        ),
        quote_target=target,
    )


def build_market_making_trace_extra(
    *,
    state: SymbolState,
    params: SymbolStrategyParameters,
    plan: MarketMakingQuotePlan,
    inventory_lots: int,
    book_age_ms: float,
    spread_ticks: float,
) -> dict[str, float | int | bool | str]:
    return {
        "microprice": state.microprice,
        "local_microprice": params.local_microprice,
        "local_depth_imbalance": params.local_depth_imbalance,
        "local_multi_level_voi": params.local_multi_level_voi,
        "global_l1_imbalance": params.global_l1_imbalance,
        "global_l1_voi": params.global_l1_voi,
        "global_mid_drift": params.global_mid_drift,
        "rls_drift_prediction_ticks": params.rls_drift_prediction_ticks,
        "rls_confidence": params.rls_confidence,
        "rls_cosine_similarity": params.rls_cosine_similarity,
        "rls_prediction_variance": params.rls_prediction_variance,
        "lead_lag_shift_ticks": params.lead_lag_shift_ticks,
        "lead_lag_confidence": params.lead_lag_confidence,
        "lead_lag_edge_score": params.lead_lag_edge_score,
        "lead_lag_leader_symbol": params.lead_lag_leader_symbol,
        "pair_spread_shift_ticks": params.pair_spread_shift_ticks,
        "pair_spread_confidence": params.pair_spread_confidence,
        "pair_spread_residual_ticks": params.pair_spread_residual_ticks,
        "pair_spread_peer_symbol": params.pair_spread_peer_symbol,
        "inventory_hedge_multiplier": params.inventory_hedge_multiplier,
        "inventory_hedge_confidence": params.inventory_hedge_confidence,
        "inventory_hedge_ratio": params.inventory_hedge_ratio,
        "inventory_hedge_symbol": params.inventory_hedge_symbol,
        "trade_signed_volume": params.trade_signed_volume,
        "trade_linked_voi_score": params.trade_linked_voi_score,
        "depth_entropy": params.depth_entropy,
        "flow_entropy": params.flow_entropy,
        "entropy_confidence_score": params.entropy_confidence_score,
        "fast_maker_voi_pressure": params.fast_maker_voi_pressure,
        "slow_trade_voi_pressure": params.slow_trade_voi_pressure,
        "taker_overlay_mode": plan.taker_overlay_mode,
        "taker_overlay_size_lots": params.taker_overlay_size_lots,
        "taker_overlay_edge_ticks": params.taker_overlay_edge_ticks,
        "global_drift_shift_ticks": params.global_drift_shift_ticks,
        "drift_agreement_multiplier": params.drift_agreement_multiplier,
        "drift_inventory_bias_ticks": params.drift_inventory_bias_ticks,
        "fair_value": plan.fair_value,
        "inventory_skew": plan.inventory_skew,
        "center_shift_applied": plan.center_shift_applied,
        "front_shape_shift": plan.front_shape_shift,
        "spread": state.spread,
        "spread_ticks": spread_ticks,
        "book_age_ms": book_age_ms,
        "half_width": plan.half_width,
        "bid_half_width": plan.bid_half_width,
        "ask_half_width": plan.ask_half_width,
        "imbalance": state.book_imbalance,
        "inventory_lots": inventory_lots,
        "flatten_target_lots": plan.flatten_target_lots,
        "max_affordable_bid_flatten_lots": params.max_affordable_bid_flatten_lots,
        "gamma_inventory": params.gamma_inventory,
        "cj_inventory_skew_ticks_per_lot": params.cj_inventory_skew_ticks_per_lot,
        "cj_horizon_fraction": params.cj_horizon_fraction,
        "glft_half_width_ticks": params.glft_half_width_ticks,
        "glft_arrival_intensity": params.glft_arrival_intensity,
        "glft_depth_sensitivity": params.glft_depth_sensitivity,
        "quote_size_lots": params.quote_size_lots,
        "passive_ladder_depth_levels": params.passive_ladder_depth_levels,
        "raw_bid_size": plan.raw_bid_size,
        "raw_ask_size": plan.raw_ask_size,
        "resolved_bid_size": plan.bid_size,
        "resolved_ask_size": plan.ask_size,
        "bid_size_multiplier": params.bid_size_multiplier,
        "ask_size_multiplier": params.ask_size_multiplier,
        "bid_width_multiplier": params.bid_width_multiplier,
        "ask_width_multiplier": params.ask_width_multiplier,
        "symbol_enable_flag": params.symbol_enable_flag,
        "bid_enable_flag": params.bid_enable_flag,
        "ask_enable_flag": params.ask_enable_flag,
        "passive_fill_probability": params.passive_fill_probability,
        "passive_fill_arrival_ms": params.passive_fill_arrival_ms,
        "fill_arrival_speed_score": params.fill_arrival_speed_score,
        "queue_fill_support": params.queue_fill_support,
        "queue_latency_haircut": params.queue_latency_haircut,
        "bid_queue_ahead_lots": params.bid_queue_ahead_lots,
        "ask_queue_ahead_lots": params.ask_queue_ahead_lots,
        "bid_queue_share": params.bid_queue_share,
        "ask_queue_share": params.ask_queue_share,
        "toxicity_score": params.toxicity_score,
        "toxicity_markout_pct": params.toxicity_markout_pct,
        "toxicity_width_multiplier": params.toxicity_width_multiplier,
        "toxicity_size_multiplier": params.toxicity_size_multiplier,
        "sigma_realized": params.sigma_realized,
        "live_quote_age_ms": params.live_quote_age_ms,
        "recent_fill_rate": params.recent_fill_rate,
        "recent_cancel_rate": params.recent_cancel_rate,
        "bid_book_volume_lk": params.bid_book_volume_lk,
        "ask_book_volume_lk": params.ask_book_volume_lk,
        "depth_baseline_lk": params.depth_baseline_lk,
        "depth_zscore": params.depth_zscore,
        "bid_25pct_levels": params.bid_25pct_levels,
        "ask_25pct_levels": params.ask_25pct_levels,
        "depth_concentration_score": params.depth_concentration_score,
        "front_shape_imbalance": params.front_shape_imbalance,
        "front_shape_shift_ticks": params.front_shape_shift_ticks,
        "side_size_tilt": params.side_size_tilt,
        "side_width_tilt": params.side_width_tilt,
        "session_elapsed_fraction": params.session_elapsed_fraction,
        "session_minutes_to_close": params.session_minutes_to_close,
        "expected_trade_count": params.expected_trade_count,
        "observed_trade_count": params.observed_trade_count,
        "trade_count_ratio": params.trade_count_ratio,
        "close_urgency_multiplier": params.close_urgency_multiplier,
        "flatten_only_mode": params.flatten_only_mode,
        "safe_mode": params.safe_mode,
        "spread_mean_ticks": params.spread_mean_ticks,
        "spread_std_ticks": params.spread_std_ticks,
        "spread_p90_ticks": params.spread_p90_ticks,
        "spread_zscore": params.spread_zscore,
        "local_imbalance_zscore": params.local_imbalance_zscore,
        "one_sided_obi_zscore": params.one_sided_obi_zscore,
        "global_drift_zscore": params.global_drift_zscore,
        "spread_regime_signal": params.spread_regime_signal,
        "global_drift_regime_signal": params.global_drift_regime_signal,
        "quote_age_mean_ms": params.quote_age_mean_ms,
        "quote_age_p90_ms": params.quote_age_p90_ms,
        "estimated_rebate": params.estimated_rebate,
        "estimated_fee": params.estimated_fee,
        "estimated_net_fee": params.estimated_net_fee,
        "passive_fill_ratio": params.passive_fill_ratio,
        "avg_net_fee_per_fill": params.avg_net_fee_per_fill,
        "execution_cost_score": params.execution_cost_score,
        "expected_passive_slippage_ticks": params.expected_passive_slippage_ticks,
        "expected_aggressive_slippage_ticks": (
            params.expected_aggressive_slippage_ticks
        ),
        "maker_net_edge_ticks": params.maker_net_edge_ticks,
        "maker_edge_intensity_factor": params.maker_edge_intensity_factor,
        "slippage_quality_score": params.slippage_quality_score,
        "realized_symbol_pnl": params.realized_symbol_pnl,
        "pnl_allocation_score": params.pnl_allocation_score,
        "inventory_close_penalty": params.inventory_close_penalty,
        "inventory_pressure_score": params.inventory_pressure_score,
        "estimated_reserved_buying_power": params.estimated_reserved_buying_power,
        "estimated_short_close_buying_power": (
            params.estimated_short_close_buying_power
        ),
        "estimated_available_buying_power": (
            params.estimated_available_buying_power
        ),
        "buying_power_usage_ratio": params.buying_power_usage_ratio,
        "buying_power_scale": params.buying_power_scale,
        "fast_velocity_ticks": params.fast_velocity_ticks,
        "slow_velocity_ticks": params.slow_velocity_ticks,
        "queue_velocity": params.queue_velocity,
        "liquidity_mass_norm": params.liquidity_mass_norm,
        "impact_mass_norm": params.impact_mass_norm,
        "physics_momentum_shift_ticks": params.physics_momentum_shift_ticks,
        "return_zscore": params.return_zscore,
        "mean_reversion_score": params.mean_reversion_score,
        "noise_fade_shift_ticks": params.noise_fade_shift_ticks,
        "mr_error_fast_ticks": params.mr_error_fast_ticks,
        "mr_error_medium_ticks": params.mr_error_medium_ticks,
        "mr_error_slow_ticks": params.mr_error_slow_ticks,
        "mr_reversion_quality_fast": params.mr_reversion_quality_fast,
        "mr_reversion_quality_medium": params.mr_reversion_quality_medium,
        "mr_reversion_quality_slow": params.mr_reversion_quality_slow,
        "mr_crossed_fast": params.mr_crossed_fast,
        "mr_crossed_medium": params.mr_crossed_medium,
        "mr_crossed_slow": params.mr_crossed_slow,
        "mr_cross_direction": params.mr_cross_direction,
        "mr_cross_depth": params.mr_cross_depth,
        "mr_cross_anchor_price": params.mr_cross_anchor_price,
        "sweep_cross_direction": params.sweep_cross_direction,
        "sweep_cross_depth": params.sweep_cross_depth,
        "sweep_cross_anchor_tau_s": params.sweep_cross_anchor_tau_s,
        "sweep_cross_anchor_price": params.sweep_cross_anchor_price,
        "noise_fade_taker_mode": params.noise_fade_taker_mode,
        "noise_fade_taker_size_lots": params.noise_fade_taker_size_lots,
        "noise_fade_ma_price": params.noise_fade_ma_price,
        "noise_fade_bid_px": params.noise_fade_bid_px,
        "noise_fade_ask_px": params.noise_fade_ask_px,
        "sleeve_weight_base_mm": params.sleeve_weight_base_mm,
        "sleeve_weight_lead_lag": params.sleeve_weight_lead_lag,
        "sleeve_weight_pair_spread": params.sleeve_weight_pair_spread,
        "sleeve_weight_inv_hedge": params.sleeve_weight_inv_hedge,
        "sleeve_weight_taker_exit": params.sleeve_weight_taker_exit,
        "sleeve_weight_noise_fade": params.sleeve_weight_noise_fade,
        "sleeve_weight_cash": params.sleeve_weight_cash,
        "sleeve_credit_base_mm": params.sleeve_credit_base_mm,
        "sleeve_credit_lead_lag": params.sleeve_credit_lead_lag,
        "sleeve_credit_pair_spread": params.sleeve_credit_pair_spread,
        "sleeve_credit_inv_hedge": params.sleeve_credit_inv_hedge,
        "sleeve_credit_taker_exit": params.sleeve_credit_taker_exit,
        "sleeve_credit_noise_fade": params.sleeve_credit_noise_fade,
        "inventory_target_lots": params.inventory_target_lots,
        "sweep_deviation_ticks": params.sweep_deviation_ticks,
        "sweep_short_ma_price": params.sweep_short_ma_price,
        "sweep_long_ma_price": params.sweep_long_ma_price,
        "sweep_detected": params.sweep_detected,
        "sweep_reversion_bid_px": params.sweep_reversion_bid_px,
        "sweep_reversion_ask_px": params.sweep_reversion_ask_px,
        "sweep_reversion_mode": params.sweep_reversion_mode,
        "sweep_reversion_size_lots": params.sweep_reversion_size_lots,
        "sweep_exit_mode": params.sweep_exit_mode,
        "sweep_exit_lots": params.sweep_exit_lots,
        "sweep_exit_side_sign": params.sweep_exit_side_sign,
        "sweep_exit_trigger": params.sweep_exit_trigger,
        "sweep_fill_price": params.sweep_fill_price,
    }
